name: Push-to-EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
  steps:
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            npm install
            npm build
            npm i serve
            serve -p 3000 build/

    