name: Push-to-EC2
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        with:
            remote_host: ${{ secrets.HOST_DNS }}
            remote_username: ${{ secrets.USERNAME }}
            ssh_private_key: ${{ secrets.EC2_SSH_KEY }}
            script_before: |
              cd ${{ secrets.TARGET_DIR }}
              npm install
              npm build
              npm i serve
              serve -p 3000 build/

      