name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    # strategy:
    #   matrix:
    #     node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - run: ls -a
      - run: npm install
      - run: npm ci
      - run: npm start
      # - run: npm run build
      # - run: cd client && npm run test
      # - run: npm i serve
      # - run: serve -s build
      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@5.1
      #   with:
      #     switches: -avzr --delete
      #     path: ./*
      #     remote_path: /root/book-store/
      #     remote_host: ${{ secrets.HOST_DNS }}
      #     remote_user: root
      #     remote_key: "${{ secrets.EC2_SSH_KEY }}"
